name: Build Latest Stable Kernel

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-build:
    uses: ./.github/workflows/build-kernel.yml
    with:
      kernel_version: '7.0'
      apply_bbr3_patch: false
      config_file: 'config'
      release_tag_prefix: 'v'
      release_name_prefix: 'Linux Kernel'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
